name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/python_docker_pr.yml@1.13.0
    secrets: inherit
    with:
      severity_for_sarif_trivy: "CRITICAL,HIGH,MEDIUM"
      limit_severities_for_sarif_trivy: true
